github:
  description: "OpenOffice.org Website"
  homepage: "https://www.openoffice.org/"
  labels:
    - openoffice
    - website
    - jbake
   
notifications:
  commits:      commits@openoffice.apache.org
  issues:       dev@openoffice.apache.org
  pullrequests: dev@openoffice.apache.org
