---
# https://pre-commit.com/
default_stages: [pre-commit, pre-push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_pre_commit_version: "3.2.0"
repos:
  - repo: meta
    hooks:
      - id: identity
        name: run identity
        description: check your identity
      - id: check-hooks-apply
        name: run check-hooks-apply
        description: check hooks apply to the repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: \.xml$
